// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-conversations.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_conversations_default = defineTool({
  name: "list_conversations",
  title: "List conversations",
  description: "List the signed-in user's ORBIT chat conversations, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max conversations to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client(ctx).from("conversations").select("id, title, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { conversations: data ?? [] } };
  }
});

// src/lib/mcp/tools/get-conversation-messages.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_conversation_messages_default = defineTool2({
  name: "get_conversation_messages",
  title: "Get conversation messages",
  description: "Return messages from one of the user's ORBIT conversations, oldest first.",
  inputSchema: {
    conversation_id: z2.string().uuid().describe("Conversation id to fetch messages for."),
    limit: z2.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client2(ctx).from("messages").select("id, role, content, created_at").eq("conversation_id", conversation_id).order("created_at", { ascending: true }).limit(limit ?? 100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { messages: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-memories.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_memories_default = defineTool3({
  name: "list_memories",
  title: "List memories",
  description: "List the user's saved ORBIT long-term memories.",
  inputSchema: { limit: z3.number().int().min(1).max(200).optional() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client3(ctx).from("user_memories").select("id, memory_type, memory_key, memory_value, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { memories: data ?? [] } };
  }
});

// src/lib/mcp/tools/save-memory.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var save_memory_default = defineTool4({
  name: "save_memory",
  title: "Save memory",
  description: "Save or update a long-term memory for the signed-in user. Do not store medical diagnoses, medications, or mental health conditions.",
  inputSchema: {
    memory_type: z4.string().min(1).describe("Category (e.g. preference, fact, context)."),
    memory_key: z4.string().min(1).describe("Stable key for this memory."),
    memory_value: z4.string().min(1).describe("Memory value / content.")
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ memory_type, memory_key, memory_value }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = client4(ctx);
    const user_id = ctx.getUserId();
    const { data: existing } = await supabase.from("user_memories").select("id").eq("user_id", user_id).eq("memory_key", memory_key).maybeSingle();
    if (existing?.id) {
      const { data: data2, error: error2 } = await supabase.from("user_memories").update({ memory_type, memory_value, updated_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", existing.id).select().single();
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      return { content: [{ type: "text", text: "Memory updated." }], structuredContent: { memory: data2 } };
    }
    const { data, error } = await supabase.from("user_memories").insert({ user_id, memory_type, memory_key, memory_value }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: "Memory saved." }], structuredContent: { memory: data } };
  }
});

// src/lib/mcp/tools/list-journal-entries.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^4.4.3";
function client5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_journal_entries_default = defineTool5({
  name: "list_journal_entries",
  title: "List journal entries",
  description: "List the user's ORBIT journal entries, newest first.",
  inputSchema: { limit: z5.number().int().min(1).max(100).optional() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client5(ctx).from("journal_entries").select("id, title, content, prompt, mood_tag, created_at, updated_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { entries: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-journal-entry.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z6 } from "npm:zod@^4.4.3";
function client6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_journal_entry_default = defineTool6({
  name: "create_journal_entry",
  title: "Create journal entry",
  description: "Create a new journal entry for the signed-in user.",
  inputSchema: {
    content: z6.string().min(1),
    title: z6.string().optional(),
    prompt: z6.string().optional(),
    mood_tag: z6.string().optional()
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ content, title, prompt, mood_tag }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client6(ctx).from("journal_entries").insert({ user_id: ctx.getUserId(), content, title, prompt, mood_tag }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: "Journal entry created." }], structuredContent: { entry: data } };
  }
});

// src/lib/mcp/tools/log-mood.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z7 } from "npm:zod@^4.4.3";
function client7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_mood_default = defineTool7({
  name: "log_mood",
  title: "Log mood",
  description: "Log a mood entry for the signed-in user.",
  inputSchema: {
    mood: z7.string().min(1).describe("Short mood label (e.g. happy, anxious)."),
    mood_score: z7.number().int().min(1).max(10).describe("1-10 score."),
    note: z7.string().optional()
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ mood, mood_score, note }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client7(ctx).from("mood_entries").insert({ user_id: ctx.getUserId(), mood, mood_score, note }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: "Mood logged." }], structuredContent: { entry: data } };
  }
});

// src/lib/mcp/tools/list-moods.ts
import { createClient as createClient8 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z8 } from "npm:zod@^4.4.3";
function client8(ctx) {
  return createClient8(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_moods_default = defineTool8({
  name: "list_moods",
  title: "List mood entries",
  description: "List the user's recent mood entries, newest first.",
  inputSchema: { limit: z8.number().int().min(1).max(100).optional() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client8(ctx).from("mood_entries").select("id, mood, mood_score, note, created_at").order("created_at", { ascending: false }).limit(limit ?? 30);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { entries: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ltqmuqozsqncdzzhkxwj";
var mcp_default = defineMcp({
  name: "orbit-mcp",
  title: "ORBIT",
  version: "0.1.0",
  instructions: "Tools for ORBIT \u2014 the user's personal AI assistant. Read/write access to the signed-in user's conversations, memories, journal entries, and mood log. All calls are scoped to the authenticated user via RLS. Never store medical diagnoses, medications, or mental health conditions in memories.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_conversations_default,
    get_conversation_messages_default,
    list_memories_default,
    save_memory_default,
    list_journal_entries_default,
    create_journal_entry_default,
    log_mood_default,
    list_moods_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
